import type { Client, Booking, PaymentMilestone } from "@/types"

// Generate dates relative to now
const now = new Date()
const daysAgo = (days: number) => {
  const date = new Date(now)
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const daysFromNow = (days: number) => {
  const date = new Date(now)
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

export const mockClients: Client[] = [
  {
    id: "client-1",
    photographer_id: "photographer-1",
    name: "Sarah & John Mitchell",
    email: "sarah.mitchell@email.com",
    phone: "(555) 123-4567",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Referred by wedding planner. Very organized.",
    created_at: daysAgo(120),
    updated_at: daysAgo(5),
  },
  {
    id: "client-2",
    photographer_id: "photographer-1",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "(555) 234-5678",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Family photographer. Books quarterly sessions.",
    created_at: daysAgo(200),
    updated_at: daysAgo(15),
  },
  {
    id: "client-3",
    photographer_id: "photographer-1",
    name: "Michael & Jennifer Chen",
    email: "mchen@email.com",
    phone: "(555) 345-6789",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Engagement session. Planning wedding for next year.",
    created_at: daysAgo(60),
    updated_at: daysAgo(2),
  },
  {
    id: "client-4",
    photographer_id: "photographer-1",
    name: "David Thompson",
    email: "david.thompson@email.com",
    phone: "(555) 456-7890",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Corporate headshots. Regular client.",
    created_at: daysAgo(300),
    updated_at: daysAgo(30),
  },
  {
    id: "client-5",
    photographer_id: "photographer-1",
    name: "Amanda & Robert Williams",
    email: "amanda.w@email.com",
    phone: "(555) 567-8901",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "New inquiry. Interested in wedding package.",
    created_at: daysAgo(10),
    updated_at: daysAgo(10),
  },
  {
    id: "client-6",
    photographer_id: "photographer-1",
    name: "Lisa Martinez",
    email: "lisa.m@email.com",
    phone: "(555) 678-9012",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Maternity and newborn photographer. Books multiple sessions.",
    created_at: daysAgo(150),
    updated_at: daysAgo(20),
  },
  {
    id: "client-7",
    photographer_id: "photographer-1",
    name: "James & Maria Anderson",
    email: "james.anderson@email.com",
    phone: "(555) 789-0123",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Anniversary session. Very happy with previous work.",
    created_at: daysAgo(90),
    updated_at: daysAgo(7),
  },
  {
    id: "client-8",
    photographer_id: "photographer-1",
    name: "Rachel Green",
    email: "rachel.g@email.com",
    phone: "(555) 890-1234",
    address: null,
    city: null,
    state: null,
    zip: null,
    country: null,
    notes: "Portrait session. Social media influencer.",
    created_at: daysAgo(45),
    updated_at: daysAgo(3),
  },
]

const createPaymentMilestones = (
  totalPrice: number,
  depositAmount: number,
  statuses: ("pending" | "paid" | "overdue")[]
): PaymentMilestone[] => {
  const milestones: PaymentMilestone[] = []

  // Deposit milestone
  milestones.push({
    id: `milestone-deposit-${Date.now()}`,
    name: "Deposit",
    amount: depositAmount,
    percentage: null,
    due_date: daysAgo(30),
    status: statuses[0] || "paid",
    paid_at: statuses[0] === "paid" ? daysAgo(25) : null,
    stripe_payment_intent_id: statuses[0] === "paid" ? "pi_demo_1" : null,
  })

  // Remaining balance milestone
  const remaining = totalPrice - depositAmount
  if (remaining > 0) {
    milestones.push({
      id: `milestone-balance-${Date.now()}`,
      name: "Final Payment",
      amount: remaining,
      percentage: null,
      due_date: daysFromNow(30),
      status: statuses[1] || "pending",
      paid_at: statuses[1] === "paid" ? daysAgo(10) : null,
      stripe_payment_intent_id: statuses[1] === "paid" ? "pi_demo_2" : null,
    })
  }

  return milestones
}

export const mockBookings: (Booking & { client?: Client })[] = [
  {
    id: "booking-1",
    photographer_id: "photographer-1",
    client_id: "client-1",
    service_type: "wedding",
    event_date: daysFromNow(45),
    event_location: null,
    total_price: 5000,
    contract_template_id: "template-1",
    contract_text: "Wedding photography contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(20),
    contract_signed_by: "sarah.mitchell@email.com",
    client_signature_name: "Sarah Mitchell",
    signature_ip_address: "192.168.1.1",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(5000, 1500, ["paid", "pending"]),
    payment_status: "DEPOSIT_PAID",
    deposit_amount: 1500,
    payment_due_date: daysFromNow(30),
    client_email: "sarah.mitchell@email.com",
    last_reminder_sent: null,
    portal_token: "token-1",
    inquiry_message: "We're getting married! Looking for a photographer for our June wedding.",
    status: "contract_signed",
    stripe_payment_intent_id: "pi_demo_1",
    created_at: daysAgo(60),
    updated_at: daysAgo(20),
    client: mockClients[0],
  },
  {
    id: "booking-2",
    photographer_id: "photographer-1",
    client_id: "client-2",
    service_type: "portrait",
    event_date: daysAgo(15),
    event_location: null,
    total_price: 850,
    contract_template_id: "template-2",
    contract_text: "Family portrait session contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(30),
    contract_signed_by: "emily.r@email.com",
    client_signature_name: "Emily Rodriguez",
    signature_ip_address: "192.168.1.2",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(850, 0, ["paid"]),
    payment_status: "paid",
    deposit_amount: 0,
    payment_due_date: daysAgo(10),
    client_email: "emily.r@email.com",
    last_reminder_sent: null,
    portal_token: "token-2",
    inquiry_message: null,
    status: "completed",
    stripe_payment_intent_id: "pi_demo_2",
    created_at: daysAgo(45),
    updated_at: daysAgo(15),
    client: mockClients[1],
  },
  {
    id: "booking-3",
    photographer_id: "photographer-1",
    client_id: "client-3",
    service_type: "portrait",
    event_date: daysAgo(5),
    event_location: null,
    total_price: 600,
    contract_template_id: "template-2",
    contract_text: "Engagement session contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(20),
    contract_signed_by: "mchen@email.com",
    client_signature_name: "Michael Chen",
    signature_ip_address: "192.168.1.3",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(600, 0, ["pending"]),
    payment_status: "pending",
    deposit_amount: 0,
    payment_due_date: daysAgo(2),
    client_email: "mchen@email.com",
    last_reminder_sent: daysAgo(1),
    portal_token: "token-3",
    inquiry_message: null,
    status: "contract_signed",
    stripe_payment_intent_id: null,
    created_at: daysAgo(30),
    updated_at: daysAgo(1),
    client: mockClients[2],
  },
  {
    id: "booking-4",
    photographer_id: "photographer-1",
    client_id: "client-4",
    service_type: "event",
    event_date: daysFromNow(60),
    event_location: null,
    total_price: 2500,
    contract_template_id: "template-3",
    contract_text: "Corporate event photography contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(10),
    contract_signed_by: "david.thompson@email.com",
    client_signature_name: "David Thompson",
    signature_ip_address: "192.168.1.4",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(2500, 750, ["paid", "pending"]),
    payment_status: "DEPOSIT_PAID",
    deposit_amount: 750,
    payment_due_date: daysFromNow(45),
    client_email: "david.thompson@email.com",
    last_reminder_sent: null,
    portal_token: "token-4",
    inquiry_message: null,
    status: "contract_signed",
    stripe_payment_intent_id: "pi_demo_3",
    created_at: daysAgo(40),
    updated_at: daysAgo(10),
    client: mockClients[3],
  },
  {
    id: "booking-5",
    photographer_id: "photographer-1",
    client_id: "client-5",
    service_type: "wedding",
    event_date: daysFromNow(90),
    event_location: null,
    total_price: 6000,
    contract_template_id: null,
    contract_text: null,
    contract_signed: false,
    contract_signed_at: null,
    contract_signed_by: null,
    client_signature_name: null,
    signature_ip_address: null,
    signature_user_agent: null,
    payment_milestones: [],
    payment_status: "pending",
    deposit_amount: null,
    payment_due_date: null,
    client_email: "amanda.w@email.com",
    last_reminder_sent: null,
    portal_token: "token-5",
    inquiry_message: "We're planning our wedding and would love to discuss photography packages!",
    status: "Inquiry",
    stripe_payment_intent_id: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(10),
    client: mockClients[4],
  },
  {
    id: "booking-6",
    photographer_id: "photographer-1",
    client_id: "client-6",
    service_type: "portrait",
    event_date: daysFromNow(20),
    event_location: null,
    total_price: 1200,
    contract_template_id: "template-2",
    contract_text: "Maternity session contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(5),
    contract_signed_by: "lisa.m@email.com",
    client_signature_name: "Lisa Martinez",
    signature_ip_address: "192.168.1.5",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(1200, 400, ["paid", "pending"]),
    payment_status: "DEPOSIT_PAID",
    deposit_amount: 400,
    payment_due_date: daysFromNow(15),
    client_email: "lisa.m@email.com",
    last_reminder_sent: null,
    portal_token: "token-6",
    inquiry_message: null,
    status: "contract_signed",
    stripe_payment_intent_id: "pi_demo_4",
    created_at: daysAgo(25),
    updated_at: daysAgo(5),
    client: mockClients[5],
  },
  {
    id: "booking-7",
    photographer_id: "photographer-1",
    client_id: "client-7",
    service_type: "portrait",
    event_date: daysAgo(30),
    event_location: null,
    total_price: 450,
    contract_template_id: "template-2",
    contract_text: "Anniversary session contract...",
    contract_signed: true,
    contract_signed_at: daysAgo(40),
    contract_signed_by: "james.anderson@email.com",
    client_signature_name: "James Anderson",
    signature_ip_address: "192.168.1.6",
    signature_user_agent: "Mozilla/5.0...",
    payment_milestones: createPaymentMilestones(450, 0, ["paid"]),
    payment_status: "paid",
    deposit_amount: 0,
    payment_due_date: daysAgo(25),
    client_email: "james.anderson@email.com",
    last_reminder_sent: null,
    portal_token: "token-7",
    inquiry_message: null,
    status: "completed",
    stripe_payment_intent_id: "pi_demo_5",
    created_at: daysAgo(50),
    updated_at: daysAgo(30),
    client: mockClients[6],
  },
  {
    id: "booking-8",
    photographer_id: "photographer-1",
    client_id: "client-8",
    service_type: "portrait",
    event_date: daysFromNow(10),
    event_location: null,
    total_price: 800,
    contract_template_id: "template-2",
    contract_text: "Portrait session contract...",
    contract_signed: false,
    contract_signed_at: null,
    contract_signed_by: null,
    client_signature_name: null,
    signature_ip_address: null,
    signature_user_agent: null,
    payment_milestones: [],
    payment_status: "pending",
    deposit_amount: null,
    payment_due_date: null,
    client_email: "rachel.g@email.com",
    last_reminder_sent: null,
    portal_token: "token-8",
    inquiry_message: null,
    status: "PROPOSAL_SENT",
    stripe_payment_intent_id: null,
    created_at: daysAgo(20),
    updated_at: daysAgo(3),
    client: mockClients[7],
  },
]

export const mockStats = {
  totalClients: 24,
  totalBookings: 18,
  pendingPayments: 12500,
  projectedRevenue: 8500,
}



