-- Add AI review tracking fields to contract_templates table
-- These fields help track AI-generated templates and their review status

-- Add last_ai_review_at timestamp (nullable, tracks when template was last reviewed by AI)
ALTER TABLE contract_templates
ADD COLUMN IF NOT EXISTS last_ai_review_at TIMESTAMPTZ;

-- Add ai_generated boolean (tracks if template was generated by AI)
ALTER TABLE contract_templates
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;

-- Add risk_score integer (0-100, stores calculated risk score from AI review)
ALTER TABLE contract_templates
ADD COLUMN IF NOT EXISTS risk_score INTEGER;

-- Add check constraint for risk_score (0-100)
ALTER TABLE contract_templates
ADD CONSTRAINT check_risk_score_range CHECK (risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100));

-- Add index for ai_generated for faster queries
CREATE INDEX IF NOT EXISTS idx_contract_templates_ai_generated 
ON contract_templates(ai_generated);

-- Add index for risk_score for filtering/sorting
CREATE INDEX IF NOT EXISTS idx_contract_templates_risk_score 
ON contract_templates(risk_score);

-- Add comments for documentation
COMMENT ON COLUMN contract_templates.last_ai_review_at IS 'Timestamp of last AI review/optimization';
COMMENT ON COLUMN contract_templates.ai_generated IS 'Whether this template was generated by AI';
COMMENT ON COLUMN contract_templates.risk_score IS 'Risk score (0-100) calculated from AI review, where 0-40 is high risk, 41-70 is moderate, 71-100 is professional grade';



